apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simpledns.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    helm.sh/chart: {{ $.Chart.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
    app: {{ $.Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "simpledns.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}      
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "simpledns.name" . }}
        helm.sh/chart: {{ include "simpledns.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/part-of: {{ include "simpledns.name" . }}
        app: {{ include "simpledns.fullname" . }}      
    spec:
      imagePullSecrets: 
        - name: {{ .Values.image.imagePullSecret }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: WEBMIN_ENABLED
            value: "true"
          - name: ROOT_PASSWORD
            value: "swisslog"
          - name: name
            value: bind
          - name: "dns"
            value: "127.0.0.1"
          - name: publish
            value: "10.49.145.194:53:53/udp"
          - name: publish
            value: "10000:10000"
          ports:
          - containerPort: 53
            protocol: UDP
          - containerPort: 53
            protocol: TCP
          - containerPort: 10000
          volumeMounts:
          - mountPath: /data
            name: bind-pvc
          resources:
{{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: bind-pvc
        persistentVolumeClaim:
          claimName: bind-pvc